

server:
  port: 8081

  max-http-request-header-size: 16KB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: STUDENT-GATEWAY-SERVICE 
    
  cloud:
    gateway:
     routes:
        - id: STUDENT-SERVICE   # Route ID for the student service
          uri: lb://STUDENT-SERVICE  # 'lb://' means load balanced, pointing to Eureka service name
          predicates:
            - Path=/student/**,/course/**

        - id: HOME-SERVICE   # Route ID for the student service
          uri: lb://HOME-SERVICE  # 'lb://' means load balanced, pointing to Eureka service name
          predicates:
            - Path=/home/**

        - id: SCHOOL-SERVICE   # Route ID for the student service
          uri: lb://SCHOOL-SERVICE  # 'lb://' means load balanced, pointing to Eureka service name
          predicates:
            - Path=/school/**